# Generated by Django 6.0.5 on 2026-06-01 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0001_initial'),
        ('org', '0002_room'),
        ('students', '0002_studentprofile_delete_studentitem_and_more'),
        ('teachers', '0002_teacherprofile_delete_teacheritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, max_length=120)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='org.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts', to='org.department')),
                ('primary_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cohorts', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CohortMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cohorts.cohort')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_memberships', to='students.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CohortTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_teachers', to='cohorts.cohort')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_teaching', to='teachers.teacherprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='CohortItem',
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['branch', 'is_archived'], name='cohorts_coh_branch__a1f822_idx'),
        ),
        migrations.AddConstraint(
            model_name='cohortmembership',
            constraint=models.UniqueConstraint(fields=('cohort', 'student'), name='unique_cohort_student'),
        ),
        migrations.AddConstraint(
            model_name='cohortteacher',
            constraint=models.UniqueConstraint(fields=('cohort', 'teacher'), name='unique_cohort_teacher'),
        ),
    ]
