# Generated by Django 6.0.5 on 2026-05-31 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_room'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('applicant', 'Applicant'), ('accepted', 'Accepted'), ('enrolled', 'Enrolled'), ('active', 'Active'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], default='lead', max_length=16)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('academic_level', models.CharField(blank=True, max_length=120)),
                ('medical_notes', models.TextField(blank=True)),
                ('emergency_contacts', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='org.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='StudentItem',
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['status'], name='students_st_status_6012f4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['branch', 'status'], name='students_st_branch__ba9f86_idx'),
        ),
    ]
