"""Reception domain: student CRUD, auto ID, permissions, branch scoping, search."""

from __future__ import annotations

from django_tenants.test.cases import TenantTestCase
from rest_framework.test import APIClient

from apps.org.models import Branch
from apps.students.models import StudentProfile
from apps.users.models import RoleMembership, User
from core.permissions import Role


class ReceptionTest(TenantTestCase):
    @classmethod
    def setup_tenant(cls, tenant):
        tenant.name = "Test Center"
        tenant.slug = "test"

    def setUp(self):
        self.host = self.get_test_tenant_domain()
        self.branch_a = Branch.objects.create(name="Main", slug="main")
        self.branch_b = Branch.objects.create(name="Second", slug="second")

        self.registrar = User.objects.create(phone="+998900000010")
        RoleMembership.objects.create(user=self.registrar, branch=self.branch_a, role=Role.REGISTRAR)

        self.teacher_a = User.objects.create(phone="+998900000020")
        RoleMembership.objects.create(user=self.teacher_a, branch=self.branch_a, role=Role.TEACHER)

        self.nobody = User.objects.create(phone="+998900000030")
        self.student_user = User.objects.create(phone="+998900000011")

    def _client(self, user):
        c = APIClient()
        c.force_authenticate(user=user)
        return c

    def test_registrar_creates_student_with_autogenerated_id(self):
        r = self._client(self.registrar).post(
            "/api/v1/students/",
            {"user": self.student_user.id, "branch": self.branch_a.id, "status": "active"},
            format="json",
            HTTP_HOST=self.host,
        )
        assert r.status_code == 201, r.content
        assert r.json()["student_id"].startswith("2026-")
        assert StudentProfile.objects.count() == 1

    def test_student_ids_are_sequential(self):
        u2 = User.objects.create(phone="+998900000012")
        c = self._client(self.registrar)
        ids = []
        for user in (self.student_user, u2):
            r = c.post(
                "/api/v1/students/",
                {"user": user.id, "branch": self.branch_a.id},
                format="json",
                HTTP_HOST=self.host,
            )
            ids.append(r.json()["student_id"])
        assert ids[0] != ids[1]
        assert ids == sorted(ids)

    def test_user_without_role_is_forbidden(self):
        r = self._client(self.nobody).get("/api/v1/students/", HTTP_HOST=self.host)
        assert r.status_code == 403, r.content

    def test_object_scope_blocks_cross_branch_access(self):
        other = StudentProfile.objects.create(
            user=self.student_user, branch=self.branch_b, student_id="2026-09999"
        )
        # Teacher belongs to branch A only; reading a branch-B student is denied.
        r = self._client(self.teacher_a).get(f"/api/v1/students/{other.id}/", HTTP_HOST=self.host)
        assert r.status_code in (403, 404), r.content

    def test_search_by_student_id(self):
        StudentProfile.objects.create(user=self.student_user, branch=self.branch_a, student_id="2026-12345")
        r = self._client(self.registrar).get("/api/v1/students/?search=12345", HTTP_HOST=self.host)
        assert r.status_code == 200, r.content
        results = r.json()["results"]
        assert len(results) == 1 and results[0]["student_id"] == "2026-12345"
