# Generated by Django 6.0.5 on 2026-06-01 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_cohort_cohortmembership_cohortteacher_and_more'),
        ('org', '0002_room'),
        ('schedule', '0001_initial'),
        ('teachers', '0002_teacherprofile_delete_teacheritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=200)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='org.branch')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='scheduled', max_length=12)),
                ('series_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='org.branch')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='cohorts.cohort')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='org.room')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ('start',),
            },
        ),
        migrations.DeleteModel(
            name='ScheduleItem',
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('branch', 'date'), name='unique_branch_holiday'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['room', 'start', 'end'], name='schedule_le_room_id_8cc6a7_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'start', 'end'], name='schedule_le_teacher_c837e1_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['cohort', 'start', 'end'], name='schedule_le_cohort__524c2e_idx'),
        ),
    ]
